BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            text: '34'
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.25
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert miles to km'
    Label:
        font_size: 34
        text: '54.717'
        color: (1, 1, 0, 1)
